---
title: "PCR with data from Roediger and Karpicke, 2006a"
author: "Will Hopper "
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette:
    fig_caption: yes
    toc: true
    toc_depth: 4
params:
  inpar: TRUE
  model: RK_PCR
  routine: test
  pars: !r c("ER","LR","TR","F1","F2","Tmin")
  fixed: !r c(Tmax=60,Ta=49.5,nFeat=100,nSim=1000,nList=30,Time=420)    
vignette: >
  %\VignetteIndexEntry{Roediger and Karpicke 2006a Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup,echo=FALSE,message=FALSE,warning=FALSE}
library(optimx)
library(dplyr)
library(digest)
library(ggplot2)
library(reshape2)
library(knitr)
library(xtable)
library(whoppeR)
library(PCR)
opts_chunk$set(echo = FALSE,fig.width=8,fig.height=6,cache=FALSE, 
               warning=F, message=FALSE, fig.align='center')
```

```{r rawData}
raw <- data.frame(
  group = c("S","T","S","T","S","T","S","T"), 
  acc = c(NA,.7,.81,.75,.54,.68,.42,.56),
  timepoint = c(1,1,2,2,3,3,4,4),
  n = c(NA,30,30,30,30,30,30,30))
```

```{r functions}
RK_PCR <- function(ER=.587, LR=.0936, TR =.1, F1=.133, F2=.06, Tmin=15.7, Tmax=60, 
                   lambda=.5, Ta=49.5, nFeat=100, nSim=1000, nList=30,
                   Time=420, summarised = TRUE, bounds) {
  set.seed(456)
  mxn <-  nSim*nList #dimensions precalculation

  # we want to sample from a beta distribution with the same
  # mean and sd as binomial(N = nFeat,p=ER) distribution.
  # The problem is that the binomial is [0,nFeat], and the equations we
  # to solve for beta distributions alpha and beta from mean and sd
  # are for beta bounded between zero and 1 aka the 2 parameter beta.
  # So we need to divide the mean and varianace of the binomial by nFeat
  # and nFeat^2. Then we can use our equations, and multiply by nFeat after sampling

  binomVAR <- nFeat*ER*(1-ER)
  binomM <- nFeat*ER
  beta_pars = betaParams(mean = binomM/nFeat, sd = sqrt(binomVAR/nFeat^2))
  
  # Initial encoding
  mem <- matrix(rbeta(mxn, beta_pars$a, beta_pars$b),
                nrow=nSim,ncol=nList) * nFeat
  thresh <- matrix(rbeta(mxn, Ta,  Ta),
                   nrow=nSim,ncol=nList) * nFeat

  # practice test performance
  prac <- freeRecall(mem,thresh, Tmin = Tmin, Tmax = Tmax,
                     Time = Time, lambda=lambda)

  # study practice boost
  restudyStrengths <- study_beta(mem=mem, nFeatures=nFeat,
                            LR = LR)
  # study practice @ 5 mins 
  restudy5 <- freeRecall(restudyStrengths, thresh, Tmin = Tmin, Tmax = Tmax,
                      Time = Time, lambda=lambda)

  # test practice boost
  testStrengths <- test_beta(mem=mem,  nFeatures=nFeat,
                        thresh = thresh, acc = prac$Acc, LR = LR,
                        TR = TR)
  
  # test practice @ 5 Minutes  
  tested5 <- freeRecall(testStrengths$mem, testStrengths$thresh,
                     Tmin = Tmin, Tmax = Tmax,
                     Time = Time, lambda=lambda)

  # study practice, 1 day
  restudyStrengths  <- forget_beta(mem = restudyStrengths, FR = F1)
  restudy2d <- freeRecall(restudyStrengths, thresh, Tmin = Tmin, Tmax = Tmax,
                      Time = Time, lambda=lambda)

  # test practice, 1 day
  testStrengths$mem <- forget_beta(mem = testStrengths$mem, FR = F1)
  tested2d <- freeRecall(testStrengths$mem, testStrengths$thresh,
                     Tmin = Tmin, Tmax = Tmax,
                     Time = Time, lambda=lambda)

  # study practice, 7 days
  restudyStrengths  <- forget_beta(mem = restudyStrengths, FR = F2)
  restudy7d <- freeRecall(restudyStrengths, thresh, Tmin = Tmin, Tmax = Tmax,
                      Time = Time, lambda=lambda)

  # test practice, 7 days
  testStrengths$mem <- forget_beta(mem = testStrengths$mem, FR = F2)
  tested7d <- freeRecall(testStrengths$mem, testStrengths$thresh,
                     Tmin = Tmin, Tmax = Tmax,
                     Time = Time, lambda=lambda)  

  # Putting the output together
  order <- rbind(prac$order,restudy5$order,tested5$order,
                 restudy2d$order,tested2d$order,
                 restudy7d$order,tested7d$order)
  RT <- rbind(prac$RT,restudy5$RT,tested5$RT,
              restudy2d$RT,tested2d$RT,
              restudy7d$RT,tested7d$RT)
  RTcor <- rbind(prac$RTcor,restudy5$RTcor,tested5$RTcor,
                 restudy2d$RTcor,tested2d$RTcor,
                 restudy7d$RTcor,tested7d$RTcor)
  rec <- rbind(prac$recoverable,restudy5$recoverable,tested5$recoverable,
               restudy2d$recoverable,tested2d$recoverable,
               restudy7d$recoverable,tested7d$recoverable)
  acc <- rbind(prac$Acc,restudy5$Acc,tested5$Acc,
               restudy2d$Acc,tested2d$Acc,
               restudy7d$Acc,tested7d$Acc)

  # Sorting the output
  for (x in 1:(nrow(order))) {
    RT[x,] <- RT[x,order[x,]]
    RTcor[x,] <- RTcor[x,order[x,]]
    rec[x,] <- rec[x,order[x,]]
    acc[x,] <- acc[x,order[x,]]
  }

  # Reshaping the output
  acc <-melt(acc, varnames=c("group","memOrder"),value.name = "acc")
  RT <- melt(RT, varnames=c("group","memOrder"),value.name = "memRT")
  RTcor <- melt(RTcor, varnames=c("group","memOrder"),value.name = "obsRT")
  rec <- melt(rec, varnames=c("group","memOrder"),value.name = "rec")

  preds <- Reduce(function(x,y) left_join(x,y, by = c("group", "memOrder")),
                  x=list(acc,RT,RTcor,rec)) %>%
    mutate(group = rep(rep(c("T","S","T","S","T","S","T"),
                            each = nSim),
                        times = nList),
           sim  = rep(1:nSim, times = nrow(.)/nSim),
           timepoint = rep(rep(c(1,2,2,3,3,4,4), each = nSim),
                        times = nList),
           unrec = !rec & !acc,
           timeout = !acc & rec) %>%
    group_by(group,sim,acc) %>%
    mutate(obsOrder = 1:n(),
           obsOrder = replace(obsOrder, acc==FALSE, NA)) %>%
    select(-rec) %>% 
    ungroup() %>% 
    arrange(timepoint,group,memOrder,sim)

  # Check summarise switch
  if (summarised) {
    preds <- preds %>%
      group_by(group,timepoint) %>% 
      summarise(pred_acc = mean(acc))
  }
  return(preds)
}


g2 <- function(obs, pred, N) {
  Lc <- obs*(log(pred)) + ((1-obs)*log(1-pred))
  Lu <- obs*(log(obs)) + ((1-obs)*log(1-obs))
  err <- -sum(2*N*(Lc-Lu))
  return(err)
}

objFun <- function(free, fixed, model = params$model, obs  = raw, 
                   errorFun = g2, bounds = paramBounds) {
  
  if (!paramBounds(c(free,fixed)) | anyNA(c(free,fixed))) {
    return(1000000)
  }
  
  p <- c(as.list(c(free,fixed)), summarised=TRUE)
  preds <- do.call(model,p)
  data <- left_join(obs,preds, by = c("group","timepoint"))
  data <- data[!is.na(data$n),]
  err <- errorFun(data$acc, data$pred_acc, data$n)
  return(err)
}

routine <- function(mode) {
  if (identical(mode,"minimize")) {
    fun <- function(model, fun = objFun) {
      fit <- optimx(par = model$free[[j]],
                    fn = fun,
                    method="Nelder-Mead",
                    itnmax=1000,
                    control = list(maxit=1000,kkt=FALSE,
                                   parscale = c(1,1,1,1,1,25)),
                    model = model$modelFcn, # passed to fun
                    fixed = model$fixed, # passed to fun
                    obs = model$data) # passed to fun
      return(fit)
    }
  } else {
    fun <- function(model, fun = objFun) {
      err <- fun(free = model$free[[j]], fixed = model$fixed, 
                 obs = model$data)
      fit <- structure(data.frame(t(c(model$free[[j]], value = err))),
                       details = NULL, maximize = NULL,
                       npar = length(model$free[[j]]), follow.on=NULL,
                       class = c("optimx", "data.frame"))
      return(fit)
    }
  }
}

genBoundsList <- function(...) {
  x <- list(...)
  lapply(x, function(y) stopifnot(length(y)==2))
  x <- lapply(x,function(y) list(upper=y[1],lower=y[2]))
}

paramBounds <- function(p) {

  probability_params <- c("ER","LR","TR","FR")
  strict_positive_params <- c("Tmin","Tmax","lambda")
  above_one_params <- c("Ta","Tb")

  prob_check <- any(p[names(p) %in% probability_params] <= 0, na.rm = TRUE) ||
                any(p[names(p) %in% probability_params] >= 1, na.rm = TRUE)
  strict_pos_check <- any(p[names(p) %in% strict_positive_params] <= 0, na.rm = TRUE)
  above_one_check <- any(p[names(p) %in% above_one_params] <= 1, na.rm = TRUE)
  
  if (any(prob_check, strict_pos_check, above_one_check)) {
    return(FALSE)
  } else {
    return(TRUE)
  }
}

```


```{r set_model}
free <- list(c(ER=.585, LR=.102, TR =.09, F1=.137, F2=.064, Tmin=15.725))

if (!all(unlist(lapply(lapply(free,names), setequal, params$pars)))) {
  stop("Model specs in header don't match free parameters. Edit header or list of free parameters")
}

mname <- strsplit(as.character(params$model),"::")[[1]]
fname <- paste(mname[length(mname)],
               paste0(params$pars,collapse="_"),
               sep="_")
fpath <- file.path("data",paste(fname,'rds',sep='.'))
model <- list(free = free,
              fixed =  params$fixed,
              modelFcn = eval(parse(text=params$model)),
              data = raw)
```

```{r cacheConditions}
cacheList <- lapply(list(g2,objFun,RK_PCR,routine,params$routine), digest, algo="sha256")
opts_chunk$set(cache.extra = cacheList)
```

```{r fit,include=FALSE, cache=TRUE}

results <- vector(mode='list', length = 1)
for (j in length(results)) {
  message("Fitting...")
  results[[j]] <-  try(routine(params$routine)(model))
}
message("Fitting Complete")
```

```{r unlist_and_extract}
best_params <- lapply(results,function(x) {
  x <- as.vector(coef(x))
  names(x) <- params$pars
  return(x) }
  )
preds <- lapply(best_params, function(x) {
  args <- c(x,as.list(model$fixed), summarised = TRUE)
  do.call(RK_PCR, args)
})

data <- left_join(raw,preds[[1]], by = c("group","timepoint")) %>%
  filter(!is.na(n)) %>%
  melt(id.vars = c("group","timepoint","n"), 
       variable.name = c("type"),
       value.name = "acc")
```

## Fixed Specs
```{r fixedSpecs,results='asis'}
print(xtable(t(as.matrix(model$fixed)), digits=3,
             caption = paste("Fixed Parameters")),
      type = "html", include.rownames=FALSE, caption.placement="top")
```

## Model Results
```{r aggResults}
ggplot(data = data, mapping = aes(x=timepoint, y=acc, colour=group,shape=type)) +
    geom_point(size=6,data = filter(data,type=='acc')) +
    geom_line(aes(group=interaction(group,type)),
              data = filter(data,type=='acc'), size = 1) +
    geom_point(size=6,data = filter(data,type=='pred_acc'),color='black') +
    scale_color_discrete(name = "Conditions",
                         labels = c("Test Practice", "Study Practice")) +
    scale_shape_manual(name="", labels= c('Obs. Data','PCR Model'), values = c(19,4)) +
    scale_x_discrete("Retention Interval", 
                     labels = c("0 Mins\n(Practice Test)", "5 Mins", "2 Days","7 Days")) + 
    scale_y_continuous("Memory Accuracy", limits=c(.4,1)) +
    ggtitle('PCR vs. Roediger & Karpicke 2006b Data') +
    theme_larger(2)
```

## Best Fitting Parameters
```{r bestFit,results='asis'}
print(xtable(as.matrix(results[[1]]), digits=3,
             caption = paste("Fixed Parameters")),
      type = "html", include.rownames=FALSE, caption.placement="top")
```

## $\chi^2$ G.O.F.
```{r chisqTest, echo=TRUE}
pchisq(results[[1]]$value, 1,lower.tail=FALSE)
```
