---
title: "Reaction Time Function in PCR"
author: "Will Hopper"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{RT Functions}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup,echo=FALSE,message=FALSE,warning=FALSE}
library(dplyr)
library(ggplot2)
library(reshape2)

```

## Negative Exponential

4 parameter function: 

  - **Max RT** (y intercept)
  - **Min RT** (x asymptote)
  - **lambda** (Rate of decrease)
  - **x** (Distance to CR threshold)
  
$$ RT = T_{min} + (T_{max}-T_{min})(e^{-\lambda |x|}) $$
  
```{r neg-exp, echo=FALSE, fig.height = 7, fig.width= 7}
Tmin <- .5
Tmax <- 90
lambdas <- c(3,2,1,.75,.5,.25,.1)
x <- seq(-10,10,by=.2)
y <- sapply(lambdas, function(l) Tmin + (Tmax-Tmin)*exp(-l*abs(x))) %>%
  melt(value.name="RT") %>%
  rename(lambda=Var2) %>%
  mutate(Var1 = rep(x,times= nrow(.)/length(x)),
         lambda = lambdas[lambda]) %>%
  rename(x=Var1)
lambda_plot <- ggplot(y, aes(x=x,y=RT, color = factor(lambda))) +
  geom_line(size=.75) +
  scale_y_continuous(breaks=seq(0,90,by=10)) + 
  scale_color_discrete("Lambda") + 
  scale_x_continuous("Distance to Threshold", breaks=-10:10) + 
  ggtitle("Predicted RT for Different Lambdas")
print(lambda_plot)
```

Reaction times to distances below the threshold represent the time until the participant "gives up" on recalling and moves to a new item.
